# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
