# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 26, 12, 25, 3, 804888, tzinfo=utc), verbose_name=b'date published'),
            preserve_default=False,
        ),
    ]
