# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_comment_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
    ]
