# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
