# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0008_auto_20160728_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
