# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0009_auto_20160728_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
    ]
