# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0010_auto_20160728_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
